### ISSUE TITLE
Validate the width param

### ISSUE THREAD

**Issue by damiantomczak** [LogicSpot/Magento_ImageLoad#2]
Hi Kamil :)
In my opinion you should validate the post params in the LogicSpot_ImageLoad_IndexController::indexAction() action because now I can inject the '99999' width size and it will generate the image with 2MB size. Probably it is possible to use this for generating many big files on the server.

Good job ;)

**Comment by kamilszewczyk** [comment]
The width param is now validated, and don't allow to generate images bigger than size of original image.
However, it's still possible to generate multiple sizes of images so for image of width 2000px, someone might be able to generate 2000 different images. 
Not sure if that's really bad, and don't have solution for now
